[project]
name = "crm-drf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-googler>=0.0.20",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.13",
]
